### PR TITLE
Composer integration

### PR DESCRIPTION
**Pull request by juriansluiman**
Update module to latest changes and add composer.json for easy zf2 project integration

### CODE REVIEW

**Comment by EvanDotPro** [comment]
@DASPRiD Please merge this. :)

**Comment by juriansluiman** [comment]
IIRC, @DASPRiD wants to make the Slugifier (now the only feature of Bacon) part of zf2. I am not sure if that already happened.

**Comment by ghost** [comment]
How is the current status? Some new informations ?

**Comment by juriansluiman** [comment]
@DASPRiD if it takes too long to put the slugifier into zf2, please merge this. 

I have a composer branch at my fork, so afaik @Terrahawk and @EvanDotPro can use that one as repository in your composer.json file: https://github.com/juriansluiman/Bacon/tree/feature/composer

Something like this should work: `"dasprid/bacon": "dev-composer"`.

**Pull request closed without merging**
